import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Game from '../components/Game';
import dayjs from 'dayjs';

import path from 'path';
import { promises as fs } from 'fs';
import {
  FormattedPlayer,
  FormattedTeam,
  BasicAnswer,
  FormattedYear,
} from '../custom-types';
import Header from '../components/Header';

type HomeProps = {
  teams: FormattedTeam[];
  players: FormattedPlayer[];
  years: FormattedYear[];
  answer: BasicAnswer;
};

const Home: React.FC<HomeProps> = ({
  teams,
  players,
  answer,
  years,
}) => {
  return (
    <>
      <Head>
        <title>worldiesle</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.bodyContent}>
          <div className="inner-container inner-container--hero">
            <h1 className={styles.heroText}>
              Guess the teams, scorer and year of this iconic or
              <span className="highlighted-text-secondary">
                {' '}
                worldie
              </span>{' '}
              goal from the pictures below
            </h1>
          </div>
          <Game
            teams={teams}
            players={players}
            years={years}
            answer={answer}
          />
        </div>
      </main>
    </>
  );
};

const LAUNCH_DATE = '2023-01-04';
const START_YEAR = 1970;

export async function getStaticProps() {
  const END_YEAR = dayjs().year();
  const daysSinceLaunch = dayjs().diff(LAUNCH_DATE, 'day');

  //Find the absolute path of the json directory
  const jsonDirectory = path.join(process.cwd(), 'data');
  const teamsFile = await fs.readFile(
    jsonDirectory + '/teams.json',
    'utf8'
  );
  const playersFile = await fs.readFile(
    jsonDirectory + '/players.json',
    'utf8'
  );

  const answer: BasicAnswer = {
    dateId: 'test',
    dayNumber: 1,
    teamA: 'CHE',
    teamB: 'LIV',
    player: 'Mohamed Salah',
    year: 2020,
    competition: 'Premier League',
    link: 'http://youtube.com',
    homeTeamMatters: true,
  };

  const years: FormattedYear[] = [];
  for (let i = START_YEAR; i <= END_YEAR; i++) {
    years.push({
      id: i.toString(),
      names: [i.toString()],
    });
  }

  return {
    props: {
      teams: JSON.parse(teamsFile),
      players: JSON.parse(playersFile),
      years,
      answer,
    },
  };
}

export default Home;
