# Calls the re-validate api endpoint at midnight each day
name: Trigger NextJS revalidation on a CRON Schedule, by sending GET request to endpoint

on:
  schedule:
    # Runs "at 11:35 UTC every day" TODO: adjust for BST?
    - cron: '0 0 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: curl
        env:
          WORLDIESLE_SECRET: ${{ secrets.WORLDIESLE_SECRET }}
        uses: wei/curl@v1
        with:
          args: -X GET https://www.worldiesle.com/api/revalidate?secret=$WORLDIESLE_SECRET
